---
#- name: install the repos
#   - include_role:
#       name: repos

  - name: install all the required rpms
    yum:
      name: "{{ req_rpm }}"
      state: latest

  - name: create the group stack
    group:
      name: "{{ stack_group }}"
      state: present

  - name: create the user stack 
    user:
      name: "{{ stack_user }}"
      group: "{{ stack_group }}"
      password: "{{ stack_passwd }}" #can use vault
  
  - name: create the required directories
    file:
      state: directory
      name: "{{ item }}"
      group: "{{ stack_group }}"
    with_items:
      - /home/stack/images/
      - /home/stack/templates/


  - name: create the stack file for sudoers
    copy:
      src: stack
      dest: /etc/sudoers.d/
      mode: "{{ sudoer_perm }}"

  - name: copy over the undercloud file
    template:
      src: undercloud.conf.j2
      dest: /home/stack/undercloud.conf
      mode: "{{ sudoer_perm }}"
      group: "{{ stack_group }}"
      owner: "{{ stack_user }}"

  - name: install the undercloud
    become: yes
    become_user: stack
    shell: openstack undercloud install
    args:
      chdir: /home/stack
    async: 2700
    poll: 30

  - name: check openstack catalog list
    shell: openstack catalog list >> catalog.txt

  - name: verify neutron
    shell: neutron net-list

  - name: verify neutron 2
    shell: neutron subnet-list


