---
  - name: install the repos
    - include_role:
        name: repos

  - name: install all the required rpms
    yum:
      name: "{{ req_rpm }}"
      state: latest

  - name: create the user stack
    user:
      name: "{{ stack_user }}"
      group: "{{ stack_group }}"
      password: "{{ stack_passwd }}" #can use vault

  - name: create the stack file for sudoers
    template:
      src: undercloud.conf.j2
      dest: /home/stack/undercloud.conf
      mode: "{{ sudoer_perm }}"




